name: SAST — Semgrep PHP

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  semgrep:
    name: Analyse statique du code PHP
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Scan Semgrep PHP
        run: semgrep --config p/php --error index.php
